const FETCH_POPULAR_GAMES = 'FETCH_POPULAR_GAMES';
const FETCH_SEARCHED_GAMES = 'FETCH_SEARCHED_GAMES';
const CLEAR_SEARCHED = 'CLEAR_SEARCHED';
const FETCH_GAME_DETAILS = 'FETCH_GAME_DETAILS';
const LOADING_DETAILS = 'LOADING_DETAILS';
export {
  FETCH_POPULAR_GAMES,
  FETCH_GAME_DETAILS,
  LOADING_DETAILS,
  FETCH_SEARCHED_GAMES,
  CLEAR_SEARCHED,
};
