const FETCH_POPULAR_GAMES = 'FETCH_POPULAR_GAMES';
const FETCH_GAME_DETAILS = 'FETCH_GAME_DETAILS';
const LOADING_DETAILS = 'LOADING_DETAILS';
export { FETCH_POPULAR_GAMES, FETCH_GAME_DETAILS, LOADING_DETAILS };
